String arrivingdatabyte;  
int a=4,b=5,c=17,d=18,e=19,f=3,g=2;
void setup( )  
{  
Serial.begin(9600);  
pinMode(a,OUTPUT);
pinMode(b,OUTPUT);
pinMode(c,OUTPUT);
pinMode(d,OUTPUT);
pinMode(e,OUTPUT);
pinMode(f,OUTPUT);
pinMode(g,OUTPUT);
}  
void loop( )  
{  
if(Serial.available( ) > 0) 
 {  
    arrivingdatabyte = Serial.readStringUntil( '\n');
    if(arrivingdatabyte=="1")
     { 
       digitalWrite(a,HIGH);
       digitalWrite(b,LOW);
       digitalWrite(c,LOW);  
       digitalWrite(d,HIGH);
       digitalWrite(e,HIGH);
       digitalWrite(f,HIGH);
       digitalWrite(g,HIGH);       
     }  
     if(arrivingdatabyte=="2")
     { 
       digitalWrite(a,LOW);
       digitalWrite(b,LOW);
       digitalWrite(c,HIGH);  
       digitalWrite(d,LOW);
       digitalWrite(e,LOW);
       digitalWrite(f,HIGH);
       digitalWrite(g,LOW);       
     } 
      if(arrivingdatabyte=="3")
     { 
       digitalWrite(a,LOW);
       digitalWrite(b,LOW);
       digitalWrite(c,LOW);  
       digitalWrite(d,LOW);
       digitalWrite(e,HIGH);
       digitalWrite(f,HIGH);
       digitalWrite(g,LOW);       
     } 
      if(arrivingdatabyte=="4")
     { 
       digitalWrite(a,HIGH);
       digitalWrite(b,LOW);
       digitalWrite(c,LOW);  
       digitalWrite(d,HIGH);
       digitalWrite(e,HIGH);
       digitalWrite(f,LOW);
       digitalWrite(g,LOW);       
     } 
      if(arrivingdatabyte=="5")
     { 
       digitalWrite(a,LOW);
       digitalWrite(b,HIGH);
       digitalWrite(c,LOW);  
       digitalWrite(d,LOW);
       digitalWrite(e,HIGH);
       digitalWrite(f,LOW);
       digitalWrite(g,LOW);       
     } 
     if(arrivingdatabyte=="0")
     { 
       digitalWrite(a,LOW);
       digitalWrite(b,LOW);
       digitalWrite(c,LOW);  
       digitalWrite(d,LOW);
       digitalWrite(e,LOW);
       digitalWrite(f,LOW);
       digitalWrite(g,HIGH);       
     }      
  }
 Serial.println(arrivingdatabyte);  
}
